/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ameralwan' at '5/25/20 12:08 PM' with Gradle 2.9
 *
 * @author ameralwan, @date 5/25/20 12:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
